# Generated by Django 4.2.7 on 2025-12-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcity_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastebin',
            name='google_maps_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wastebin',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
