# Generated by Django 4.2.7 on 2025-12-26 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcity_app', '0002_alter_wastebin_google_maps_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boiler',
            old_name='target_temp',
            new_name='humidity',
        ),
        migrations.RenameField(
            model_name='boiler',
            old_name='temperature',
            new_name='target_humidity',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='target_temp',
            new_name='humidity',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='temperature',
            new_name='target_humidity',
        ),
    ]
