# Generated by Django 4.2.7 on 2025-12-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcity_app', '0003_rename_target_temp_boiler_humidity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastebin',
            name='qr_code_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
