# Generated by Django 4.2.7 on 2025-12-28 01:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('smartcity_app', '0004_wastebin_qr_code_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='boiler',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='boiler',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='boiler',
            name='temperature',
            field=models.FloatField(default=22.0),
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='smartcity_app.facility'),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='temperature',
            field=models.FloatField(default=22.0),
        ),
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('device_type', models.CharField(choices=[('TEMPERATURE_SENSOR', 'Temperature Sensor'), ('HUMIDITY_SENSOR', 'Humidity Sensor'), ('BOTH', 'Temperature and Humidity Sensor')], max_length=50)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boiler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iot_devices', to='smartcity_app.boiler')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartcity_app.coordinate')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iot_devices', to='smartcity_app.room')),
            ],
        ),
    ]
