# Generated by Django 4.2.7 on 2025-12-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcity_app', '0005_boiler_created_at_boiler_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdevice',
            name='current_humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='current_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='last_sensor_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
