# Generated by Django 4.2.7 on 2025-12-28 18:57
# Migration to change Room.id from UUIDField to CharField
# WARNING: This will recreate the Room table in SQLite, which will DELETE existing Room data!
# If you have existing Room records, back them up first or delete them manually.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcity_app', '0006_iotdevice_current_humidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.CharField(
                help_text='Room ID (e.g., 0420101 - leading zeros are preserved)',
                max_length=50,
                primary_key=True,
                serialize=False,
                unique=True,
                editable=True,
            ),
        ),
    ]
